server:
  port: 8888
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:33066/blogserver?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456

  redis:
    # 连接超时时间
    timeout: 10000ms
    host: 保密
    port: 6379
    database: 0
    lettuce:
      pool:
        # 最大连接数
        max-active: 1024
        # 最大连接等待时间
        max-wait: 10000ms
        # 最大空闲连接
        max-idle: 200
        # 最小空闲连接
        min-idle: 5

mybatis-plus:
  # 配置Mapper位置
  mapper-locations: classpath*:/mapper/*Mapper.xml
  # 配置数据返回类型的别名
  type-aliases-package: com.example.blogmaster.pojo
  configuration:
    # 关闭自动驼峰命名
    map-underscore-to-camel-case: false
  global-config:
    db-config:
      table-prefix: t_

# 打印SQL(配置的是接口所在包，不是Mapper.xml所在的包)
logging:
  level:
    com.example.blogmaster.mapper: debug

jwt:
  # jwt在请求头中的位置
  tokenHeader: Authorization
  # 签名加密密钥
  secret: Ivyevy
  # jwt过期时间(一天)
  expiration: 86400